# Generated by Django 5.2.18 on 2026-10-06 19:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occurred_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('category', models.CharField(choices=[('lines', 'Lines'), ('picks', 'Picks'), ('games', 'Games'), ('standings', 'Standings'), ('settings', 'Settings'), ('membership', 'Membership'), ('security', 'Security'), ('notifications', 'Notifications')], max_length=16)),
                ('event_type', models.CharField(max_length=48)),
                ('actor_type', models.CharField(choices=[('member', 'Member'), ('commissioner', 'Commissioner'), ('admin', 'Admin'), ('system', 'System')], max_length=16)),
                ('object_type', models.CharField(blank=True, max_length=32)),
                ('object_id', models.CharField(blank=True, max_length=64)),
                ('before', models.JSONField(blank=True, null=True)),
                ('after', models.JSONField(blank=True, null=True)),
                ('summary', models.CharField(max_length=255)),
                ('source', models.CharField(max_length=32)),
                ('request_id', models.CharField(max_length=32)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='activity_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
    ]
