# Generated by Django 5.2.18 on 2026-10-06 19:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activity', '0001_initial'),
        ('leagues', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='activityevent',
            name='league',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='activity_events', to='leagues.league'),
        ),
        migrations.AddField(
            model_name='activityevent',
            name='league_week',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='activity_events', to='leagues.leagueweek'),
        ),
        migrations.AddField(
            model_name='activityevent',
            name='subject_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='activity_events_about', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='activityevent',
            index=models.Index(fields=['league', 'occurred_at'], name='activity_ac_league__d64496_idx'),
        ),
        migrations.AddIndex(
            model_name='activityevent',
            index=models.Index(fields=['league', 'league_week', 'category'], name='activity_ac_league__194ea7_idx'),
        ),
        migrations.AddIndex(
            model_name='activityevent',
            index=models.Index(fields=['actor', 'occurred_at'], name='activity_ac_actor_i_28fb60_idx'),
        ),
        migrations.AddIndex(
            model_name='activityevent',
            index=models.Index(fields=['subject_user', 'occurred_at'], name='activity_ac_subject_c08c06_idx'),
        ),
        migrations.AddIndex(
            model_name='activityevent',
            index=models.Index(fields=['object_type', 'object_id'], name='activity_ac_object__b361ff_idx'),
        ),
    ]
