# Generated by Django 5.2.18 on 2026-10-06 20:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leagues', '0001_initial'),
        ('nfl', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OddsSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fetched_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('source', models.CharField(max_length=40)),
                ('payload', models.JSONField()),
            ],
            options={
                'ordering': ('-fetched_at',),
            },
        ),
        migrations.CreateModel(
            name='Spread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('locked', 'Locked at spread lock'), ('closing', 'Closing line')], default='locked', max_length=8)),
                ('status', models.CharField(choices=[('posted', 'Posted'), ('off', 'Off the board'), ('void', 'Void for the week')], default='posted', max_length=8)),
                ('home_line', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('feed_line', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('book_count', models.PositiveSmallIntegerField(default=0)),
                ('source', models.CharField(max_length=40)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('overridden', models.BooleanField(default=False)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='spreads', to='nfl.game')),
                ('league_season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spreads', to='leagues.leagueseason')),
            ],
            options={
                'ordering': ('game__kickoff_at',),
                'constraints': [models.UniqueConstraint(fields=('league_season', 'game', 'kind'), name='lines_spread_unique'), models.CheckConstraint(condition=models.Q(models.Q(('home_line__isnull', False), ('status', 'posted')), models.Q(('status', 'posted'), _negated=True), _connector='OR'), name='lines_spread_posted_has_line')],
            },
        ),
    ]
