# Generated by Django 5.2.18 on 2026-10-06 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(unique=True)),
            ],
            options={
                'ordering': ('-year',),
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=32, unique=True)),
                ('abbreviation', models.CharField(max_length=8)),
                ('location', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=64)),
            ],
            options={
                'ordering': ('abbreviation',),
            },
        ),
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField()),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('sunday', models.DateField()),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weeks', to='nfl.season')),
            ],
            options={
                'ordering': ('season', 'number'),
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=32, unique=True)),
                ('kickoff_at', models.DateTimeField()),
                ('kickoff_is_tbd', models.BooleanField(default=False)),
                ('postponed_from', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In progress'), ('final', 'Final'), ('postponed', 'Postponed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=16)),
                ('neutral_site', models.BooleanField(default=False)),
                ('home_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('away_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='away_games', to='nfl.team')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='home_games', to='nfl.team')),
                ('week', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='games', to='nfl.week')),
            ],
            options={
                'ordering': ('kickoff_at', 'external_id'),
            },
        ),
        migrations.AddConstraint(
            model_name='week',
            constraint=models.UniqueConstraint(fields=('season', 'number'), name='nfl_week_season_number_unique'),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['week', 'kickoff_at'], name='nfl_game_week_id_c75c07_idx'),
        ),
        migrations.AddConstraint(
            model_name='game',
            constraint=models.CheckConstraint(condition=models.Q(('home_team', models.F('away_team')), _negated=True), name='nfl_game_distinct_teams'),
        ),
    ]
