# Generated by Django 5.2.18 on 2026-10-07 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfl', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='score_overridden',
            field=models.BooleanField(default=False, help_text='A commissioner corrected the score; feed syncs leave it alone.'),
        ),
    ]
