# Generated by Django 5.2.18 on 2026-10-06 19:02

import apps.leagues.models
import datetime
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nfl', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('slug', models.SlugField(max_length=40, unique=True)),
                ('timezone', models.CharField(default='America/Los_Angeles', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='LeagueSeason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='leagues.league')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='league_seasons', to='nfl.season')),
            ],
            options={
                'ordering': ('league', '-season__year'),
            },
        ),
        migrations.CreateModel(
            name='LeagueSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pick_type', models.CharField(choices=[('against_spread', 'Against the spread'), ('straight_up', 'Straight up')], default='against_spread', max_length=20)),
                ('game_selection', models.CharField(choices=[('all_games', 'All games'), ('commissioner_slate', 'Commissioner selects games')], default='all_games', max_length=20)),
                ('points_per_win', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('best_bets_per_week', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(5)])),
                ('best_bet_bonus', models.PositiveSmallIntegerField(default=2)),
                ('best_bet_required', models.BooleanField(default=False)),
                ('best_bet_team_once_per_season', models.BooleanField(default=False)),
                ('line_mode', models.CharField(choices=[('fixed_at_lock', 'Fixed at spread lock'), ('variable', 'Line when the pick is made'), ('closing', 'Closing line')], default='fixed_at_lock', max_length=20)),
                ('spread_lock_weekday', models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], default=1)),
                ('spread_lock_time', models.TimeField(default=datetime.time(3, 0))),
                ('line_source', models.CharField(choices=[('median_us_books', 'Median of US sportsbooks')], default='median_us_books', max_length=32)),
                ('half_point_lines', models.BooleanField(default=True)),
                ('half_point_rounding', models.CharField(choices=[('favorite_gives', 'Favorite gives the half point'), ('favorite_gets', 'Favorite gets the half point')], default='favorite_gives', max_length=20)),
                ('push_scoring', models.CharField(choices=[('half_points', 'Half points'), ('loss', 'Loss'), ('win', 'Win')], default='half_points', max_length=16)),
                ('off_line_handling', models.CharField(choices=[('unpickable_until_posted', 'Unpickable until posted'), ('hold_week', 'Hold the week for the commissioner')], default='unpickable_until_posted', max_length=32)),
                ('off_line_cutoff', models.CharField(choices=[('first_kickoff_of_week', 'First kickoff of the week'), ('game_lock', "The game's own lock")], default='first_kickoff_of_week', max_length=32)),
                ('off_line_fallback', models.CharField(choices=[('void', 'Void for the week'), ('favorite_minus_half', 'Favorite -0.5'), ('pickem_straight_up', 'Straight up')], default='void', max_length=32)),
                ('picks_lock_weekday', models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], default=6)),
                ('picks_lock_time', models.TimeField(default=datetime.time(10, 0))),
                ('game_lock_offset_minutes', models.PositiveSmallIntegerField(default=0)),
                ('grace_period_hours', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('pick_visibility', models.CharField(choices=[('at_game_lock', 'When each game locks'), ('at_weekly_deadline', 'At the weekly deadline')], default='at_game_lock', max_length=20)),
                ('future_week_picks', models.BooleanField(default=False)),
                ('autopick', models.CharField(choices=[('off', 'Off'), ('random', 'Random'), ('home', 'Home team'), ('favorite', 'Favorite'), ('underdog', 'Underdog')], default='off', max_length=16)),
                ('autopick_max_weeks', models.PositiveSmallIntegerField(default=0)),
                ('autopick_tiebreaker_guess', models.PositiveSmallIntegerField(default=40)),
                ('tiebreaker_game', models.CharField(choices=[('last_game_of_week', 'Last game of the week'), ('commissioner_selects', 'Commissioner selects')], default='last_game_of_week', max_length=24)),
                ('tiebreaker_type', models.CharField(choices=[('total_points', 'Total points'), ('margin_of_victory', 'Margin of victory')], default='total_points', max_length=20)),
                ('underdog_outright_bonus', models.PositiveSmallIntegerField(default=0)),
                ('tiebreaker_exact_bonus', models.PositiveSmallIntegerField(default=0)),
                ('over_under_points', models.PositiveSmallIntegerField(default=0)),
                ('drop_worst_week', models.BooleanField(default=False)),
                ('weekly_prize_enabled', models.BooleanField(default=True)),
                ('weekly_prize_metric', models.CharField(choices=[('points', 'Points'), ('wins', 'Correct picks')], default='points', max_length=8)),
                ('season_points_prize_enabled', models.BooleanField(default=True)),
                ('season_points_prize_places', models.PositiveSmallIntegerField(default=1)),
                ('best_bet_prize_enabled', models.BooleanField(default=True)),
                ('best_bet_prize_places', models.PositiveSmallIntegerField(default=1)),
                ('prize_amounts', models.JSONField(blank=True, default=dict)),
                ('reminder_times', models.JSONField(default=apps.leagues.models.default_reminder_times)),
                ('season_type', models.CharField(choices=[('regular_season', 'Regular season')], default='regular_season', max_length=20)),
                ('league_season', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='leagues.leagueseason')),
            ],
            options={
                'verbose_name_plural': 'league settings',
            },
        ),
        migrations.CreateModel(
            name='LeagueWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spreads_lock_at', models.DateTimeField()),
                ('picks_lock_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('published', 'Published'), ('in_progress', 'In progress'), ('final', 'Final')], default='scheduled', max_length=16)),
                ('league_season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weeks', to='leagues.leagueseason')),
                ('tiebreaker_game', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='nfl.game')),
                ('week', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='league_weeks', to='nfl.week')),
            ],
            options={
                'ordering': ('league_season', 'week__number'),
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('member', 'Member'), ('commissioner', 'Commissioner')], default='member', max_length=16)),
                ('is_active', models.BooleanField(default=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='leagues.league')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('league', 'user__display_name'),
            },
        ),
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('role', models.CharField(choices=[('member', 'Member'), ('commissioner', 'Commissioner')], default='member', max_length=16)),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('invited_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='leagues.league')),
            ],
            options={
                'ordering': ('-created_at',),
                'constraints': [models.CheckConstraint(condition=models.Q(('accepted_at__isnull', True), ('revoked_at__isnull', True), _connector='OR'), name='leagues_invite_not_accepted_and_revoked')],
            },
        ),
        migrations.AddConstraint(
            model_name='leagueseason',
            constraint=models.UniqueConstraint(fields=('league', 'season'), name='leagues_leagueseason_unique'),
        ),
        migrations.AddConstraint(
            model_name='leagueweek',
            constraint=models.UniqueConstraint(fields=('league_season', 'week'), name='leagues_leagueweek_unique'),
        ),
        migrations.AddConstraint(
            model_name='membership',
            constraint=models.UniqueConstraint(fields=('user', 'league'), name='leagues_membership_unique'),
        ),
    ]
