# Generated by Django 5.2.18 on 2026-10-07 06:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leagues', '0001_initial'),
        ('nfl', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_best_bet', models.BooleanField(default=False)),
                ('home_line_at_pick', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='picks', to='nfl.game')),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='picks', to='leagues.membership')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='nfl.team')),
                ('week', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='picks', to='nfl.week')),
            ],
            options={
                'ordering': ('game__kickoff_at',),
                'indexes': [models.Index(fields=['membership', 'week'], name='picks_pick_members_34b7f2_idx')],
                'constraints': [models.UniqueConstraint(fields=('membership', 'game'), name='picks_pick_member_game_unique')],
            },
        ),
        migrations.CreateModel(
            name='WeeklyEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiebreaker_guess', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('league_week', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='leagues.leagueweek')),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='weekly_entries', to='leagues.membership')),
            ],
            options={
                'verbose_name_plural': 'weekly entries',
                'constraints': [models.UniqueConstraint(fields=('membership', 'league_week'), name='picks_weeklyentry_unique')],
            },
        ),
    ]
