# Generated by Django 5.2.18 on 2026-10-07 18:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leagues', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('week_open', 'Week open for picks'), ('reminders', 'Pick reminders'), ('weekly_results', 'Weekly results'), ('picks_entered', 'A commissioner changed my picks'), ('commissioner', 'Commissioner notices (lines to review)')], max_length=20)),
                ('key', models.CharField(blank=True, max_length=40)),
                ('sent_at', models.DateTimeField()),
                ('recipients', models.PositiveIntegerField(default=0)),
                ('league_week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispatches', to='leagues.leagueweek')),
            ],
            options={
                'ordering': ('-sent_at',),
                'constraints': [models.UniqueConstraint(fields=('kind', 'league_week', 'key'), name='notifications_dispatch_unique')],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('week_open', 'Week open for picks'), ('reminders', 'Pick reminders'), ('weekly_results', 'Weekly results'), ('picks_entered', 'A commissioner changed my picks'), ('commissioner', 'Commissioner notices (lines to review)')], max_length=20)),
                ('enabled', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'kind'), name='notifications_preference_unique')],
            },
        ),
    ]
